version: '3'

services:
  cron:
      restart: always
      build:
        context: .
        dockerfile: docker/dockerfiles/cron-alpine-dockerfile
        args:
          cron_job_run_dependencies: php7 php7-pdo_mysql php7-curl php7-json php7-session php7-bcmath php7-ctype php7-mbstring php7-openssl php7-tokenizer php7-xml
      volumes:
        - "./:/data/www/"
