version: '3'

services:
  cron:
      restart: always
      build:
        context: .
        dockerfile: docker/dockerfiles/cron-alpine-dockerfile
        args:
          cron_job_run_dependencies: 
      volumes:
        - "./:/data/www/"
